name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. Repo'yu klonla
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Flutter'ı sabit sürümle yükle ve cache kullan
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"  # Flutter 3.24 Dart 3.5 içerir
          cache: true

      # 3. Flutter bağımlılıkları ve build output cache
      - name: Cache Flutter Pub & Build
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            build
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # 4. Flutter bağımlılıklarını yükle
      - name: Install dependencies
        run: flutter pub get

      # 5. APK'yı derle
      - name: Build APK
        run: flutter build apk --release

      # 6. APK'yı artefakt olarak yükle
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
