name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. Repo'yu klonla
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Flutter'ı sabit sürümle yükle
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"  # Sabit Flutter sürümü, stable sürümüne göre güncelleyebilirsin

      # 3. Flutter bağımlılıklarını yükle
      - name: Install dependencies
        run: flutter pub get

      # 4. APK'yı derle
      - name: Build APK
        run: flutter build apk --release

      # 5. APK'yı artefakt olarak yükle (v4)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
